# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(607, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(607, 330))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/Wallpapers/Mustang in Anticipation 1920 by 1080.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(-3)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 601, 241))
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.Ethernet = QtWidgets.QWidget()
        self.Ethernet.setObjectName("Ethernet")
        self.ifacelabel = QtWidgets.QLabel(self.Ethernet)
        self.ifacelabel.setGeometry(QtCore.QRect(20, 10, 81, 17))
        self.ifacelabel.setObjectName("ifacelabel")
        self.label_2 = QtWidgets.QLabel(self.Ethernet)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 171, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Ethernet)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 201, 17))
        self.label_3.setObjectName("label_3")
        self.interface_box = QtWidgets.QComboBox(self.Ethernet)
        self.interface_box.setGeometry(QtCore.QRect(20, 30, 191, 27))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interface_box.sizePolicy().hasHeightForWidth())
        self.interface_box.setSizePolicy(sizePolicy)
        self.interface_box.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.interface_box.setMouseTracking(False)
        self.interface_box.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.interface_box.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.interface_box.setAcceptDrops(True)
        self.interface_box.setStatusTip("")
        self.interface_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.interface_box.setAutoFillBackground(True)
        self.interface_box.setStyleSheet("font: 57 italic 11pt \"Ubuntu\";")
        self.interface_box.setCurrentText("")
        self.interface_box.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.interface_box.setDuplicatesEnabled(False)
        self.interface_box.setFrame(False)
        self.interface_box.setModelColumn(0)
        self.interface_box.setObjectName("interface_box")
        self.interface_box.addItem("")
        self.source_MAC_box = QtWidgets.QComboBox(self.Ethernet)
        self.source_MAC_box.setGeometry(QtCore.QRect(20, 90, 191, 27))
        self.source_MAC_box.setAcceptDrops(False)
        self.source_MAC_box.setEditable(True)
        self.source_MAC_box.setCurrentText("")
        self.source_MAC_box.setDuplicatesEnabled(False)
        self.source_MAC_box.setFrame(True)
        self.source_MAC_box.setObjectName("source_MAC_box")
        self.dest_MAC_box = QtWidgets.QComboBox(self.Ethernet)
        self.dest_MAC_box.setGeometry(QtCore.QRect(20, 160, 191, 27))
        self.dest_MAC_box.setAcceptDrops(False)
        self.dest_MAC_box.setEditable(True)
        self.dest_MAC_box.setCurrentText("")
        self.dest_MAC_box.setDuplicatesEnabled(False)
        self.dest_MAC_box.setFrame(True)
        self.dest_MAC_box.setObjectName("dest_MAC_box")
        self.ScapyCode = QtWidgets.QTextEdit(self.Ethernet)
        self.ScapyCode.setGeometry(QtCore.QRect(360, 40, 231, 141))
        self.ScapyCode.setObjectName("ScapyCode")
        self.label_7 = QtWidgets.QLabel(self.Ethernet)
        self.label_7.setGeometry(QtCore.QRect(360, 10, 111, 17))
        self.label_7.setObjectName("label_7")
        self.help = QtWidgets.QPushButton(self.Ethernet)
        self.help.setGeometry(QtCore.QRect(490, 180, 101, 21))
        self.help.setObjectName("help")
        self.tabWidget.addTab(self.Ethernet, "")
        self.IP = QtWidgets.QWidget()
        self.IP.setObjectName("IP")
        self.iface_2 = QtWidgets.QLabel(self.IP)
        self.iface_2.setGeometry(QtCore.QRect(20, 10, 151, 17))
        self.iface_2.setObjectName("iface_2")
        self.iface_3 = QtWidgets.QLabel(self.IP)
        self.iface_3.setGeometry(QtCore.QRect(20, 90, 201, 17))
        self.iface_3.setObjectName("iface_3")
        self.source_IP_box = QtWidgets.QComboBox(self.IP)
        self.source_IP_box.setGeometry(QtCore.QRect(20, 30, 191, 27))
        self.source_IP_box.setAcceptDrops(False)
        self.source_IP_box.setEditable(True)
        self.source_IP_box.setCurrentText("")
        self.source_IP_box.setDuplicatesEnabled(False)
        self.source_IP_box.setFrame(True)
        self.source_IP_box.setObjectName("source_IP_box")
        self.source_IP_box.addItem("")
        self.source_IP_box.addItem("")
        self.dest_IP_box = QtWidgets.QComboBox(self.IP)
        self.dest_IP_box.setGeometry(QtCore.QRect(20, 110, 191, 27))
        self.dest_IP_box.setAcceptDrops(False)
        self.dest_IP_box.setEditable(True)
        self.dest_IP_box.setCurrentText("")
        self.dest_IP_box.setDuplicatesEnabled(False)
        self.dest_IP_box.setFrame(True)
        self.dest_IP_box.setObjectName("dest_IP_box")
        self.dest_IP_box.addItem("")
        self.dest_IP_box.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.IP)
        self.groupBox.setGeometry(QtCore.QRect(390, 10, 201, 191))
        self.groupBox.setObjectName("groupBox")
        self.arp_send = QtWidgets.QPushButton(self.groupBox)
        self.arp_send.setGeometry(QtCore.QRect(90, 110, 101, 27))
        self.arp_send.setObjectName("arp_send")
        self.arp_code = QtWidgets.QPushButton(self.groupBox)
        self.arp_code.setGeometry(QtCore.QRect(90, 140, 101, 27))
        self.arp_code.setObjectName("arp_code")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 30, 117, 22))
        self.radioButton.setChecked(True)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setObjectName("radioButton")
        self.arp_response_radio = QtWidgets.QRadioButton(self.groupBox)
        self.arp_response_radio.setGeometry(QtCore.QRect(20, 60, 131, 22))
        self.arp_response_radio.setChecked(False)
        self.arp_response_radio.setObjectName("arp_response_radio")
        self.line = QtWidgets.QFrame(self.IP)
        self.line.setGeometry(QtCore.QRect(360, 10, 20, 191))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.IP, "")
        self.next = QtWidgets.QWidget()
        self.next.setObjectName("next")
        self.protocolbox = QtWidgets.QComboBox(self.next)
        self.protocolbox.setGeometry(QtCore.QRect(20, 10, 85, 27))
        self.protocolbox.setObjectName("protocolbox")
        self.protocolbox.addItem("")
        self.protocolbox.addItem("")
        self.protocolbox.addItem("")
        self.label = QtWidgets.QLabel(self.next)
        self.label.setGeometry(QtCore.QRect(30, 40, 121, 31))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.next)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 121, 31))
        self.label_4.setObjectName("label_4")
        self.sourceport = QtWidgets.QLineEdit(self.next)
        self.sourceport.setGeometry(QtCore.QRect(160, 40, 61, 27))
        self.sourceport.setObjectName("sourceport")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.next)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 80, 61, 27))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_fo_flags = QtWidgets.QGroupBox(self.next)
        self.groupBox_fo_flags.setGeometry(QtCore.QRect(30, 120, 231, 80))
        self.groupBox_fo_flags.setTitle("")
        self.groupBox_fo_flags.setObjectName("groupBox_fo_flags")
        self.label_5 = QtWidgets.QLabel(self.groupBox_fo_flags)
        self.label_5.setGeometry(QtCore.QRect(10, -10, 51, 31))
        self.label_5.setObjectName("label_5")
        self.SYN = QtWidgets.QRadioButton(self.groupBox_fo_flags)
        self.SYN.setGeometry(QtCore.QRect(20, 20, 61, 22))
        self.SYN.setChecked(True)
        self.SYN.setObjectName("SYN")
        self.ACK = QtWidgets.QRadioButton(self.groupBox_fo_flags)
        self.ACK.setGeometry(QtCore.QRect(20, 40, 61, 22))
        self.ACK.setObjectName("ACK")
        self.FIN = QtWidgets.QRadioButton(self.groupBox_fo_flags)
        self.FIN.setGeometry(QtCore.QRect(160, 20, 61, 22))
        self.FIN.setObjectName("FIN")
        self.URG = QtWidgets.QRadioButton(self.groupBox_fo_flags)
        self.URG.setGeometry(QtCore.QRect(90, 40, 61, 22))
        self.URG.setObjectName("URG")
        self.PSH = QtWidgets.QRadioButton(self.groupBox_fo_flags)
        self.PSH.setGeometry(QtCore.QRect(90, 20, 61, 22))
        self.PSH.setObjectName("PSH")
        self.RST = QtWidgets.QRadioButton(self.groupBox_fo_flags)
        self.RST.setGeometry(QtCore.QRect(160, 40, 61, 22))
        self.RST.setObjectName("RST")
        self.line_2 = QtWidgets.QFrame(self.next)
        self.line_2.setGeometry(QtCore.QRect(273, 10, 20, 191))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_for_payload = QtWidgets.QGroupBox(self.next)
        self.groupBox_for_payload.setGeometry(QtCore.QRect(300, 10, 291, 181))
        self.groupBox_for_payload.setTitle("")
        self.groupBox_for_payload.setObjectName("groupBox_for_payload")
        self.label_6 = QtWidgets.QLabel(self.groupBox_for_payload)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 61, 31))
        self.label_6.setObjectName("label_6")
        self.payload_string = QtWidgets.QRadioButton(self.groupBox_for_payload)
        self.payload_string.setGeometry(QtCore.QRect(50, 50, 71, 22))
        self.payload_string.setObjectName("payload_string")
        self.payload_no = QtWidgets.QRadioButton(self.groupBox_for_payload)
        self.payload_no.setGeometry(QtCore.QRect(50, 120, 111, 22))
        self.payload_no.setChecked(True)
        self.payload_no.setObjectName("payload_no")
        self.payloadPcap = QtWidgets.QRadioButton(self.groupBox_for_payload)
        self.payloadPcap.setGeometry(QtCore.QRect(50, 90, 111, 22))
        self.payloadPcap.setObjectName("payloadPcap")
        self.stringbox = QtWidgets.QLineEdit(self.groupBox_for_payload)
        self.stringbox.setGeometry(QtCore.QRect(130, 50, 151, 27))
        self.stringbox.setObjectName("stringbox")
        self.xintotimes = QtWidgets.QLineEdit(self.groupBox_for_payload)
        self.xintotimes.setGeometry(QtCore.QRect(150, 90, 41, 27))
        self.xintotimes.setObjectName("xintotimes")
        self.tabWidget.addTab(self.next, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Clipboard = QtWidgets.QTextEdit(self.tab)
        self.Clipboard.setGeometry(QtCore.QRect(10, 20, 581, 181))
        self.Clipboard.setObjectName("Clipboard")
        self.tabWidget.addTab(self.tab, "")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(168, 246, 101, 31))
        self.send_button.setObjectName("send_button")
        self.clipboard_button = QtWidgets.QPushButton(self.centralwidget)
        self.clipboard_button.setGeometry(QtCore.QRect(288, 246, 101, 31))
        self.clipboard_button.setObjectName("clipboard_button")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(498, 246, 101, 31))
        self.exit.setObjectName("exit")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(-3, 275, 631, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 607, 25))
        self.menuBar.setDefaultUp(True)
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuEeee = QtWidgets.QMenu(self.menuBar)
        self.menuEeee.setObjectName("menuEeee")
        self.menuTtt = QtWidgets.QMenu(self.menuBar)
        self.menuTtt.setObjectName("menuTtt")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuEeee.menuAction())
        self.menuBar.addAction(self.menuTtt.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.interface_box.setCurrentIndex(-1)
        self.source_MAC_box.setCurrentIndex(-1)
        self.dest_MAC_box.setCurrentIndex(-1)
        self.source_IP_box.setCurrentIndex(-1)
        self.dest_IP_box.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Packet Crafter - V1.0"))
        self.ifacelabel.setText(_translate("MainWindow", "Interface:"))
        self.label_2.setText(_translate("MainWindow", "Source MAC Address:"))
        self.label_3.setText(_translate("MainWindow", "Destination MAC Address:"))
        self.interface_box.setItemText(0, _translate("MainWindow", "ascsd"))
        self.label_7.setText(_translate("MainWindow", "Introduction:"))
        self.help.setText(_translate("MainWindow", "Help"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Ethernet), _translate("MainWindow", "Ethernet Header"))
        self.iface_2.setText(_translate("MainWindow", "Source IP Address:"))
        self.iface_3.setText(_translate("MainWindow", "Destination IP or Hostname:"))
        self.source_IP_box.setItemText(0, _translate("MainWindow", "dap"))
        self.source_IP_box.setItemText(1, _translate("MainWindow", "eeapp"))
        self.dest_IP_box.setItemText(0, _translate("MainWindow", "dap"))
        self.dest_IP_box.setItemText(1, _translate("MainWindow", "eeapp"))
        self.groupBox.setTitle(_translate("MainWindow", "ARP"))
        self.arp_send.setText(_translate("MainWindow", "Send"))
        self.arp_code.setText(_translate("MainWindow", "Code"))
        self.radioButton.setText(_translate("MainWindow", "ARP Request"))
        self.arp_response_radio.setText(_translate("MainWindow", "ARP Response"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IP), _translate("MainWindow", "IPv4 Header"))
        self.protocolbox.setItemText(0, _translate("MainWindow", "TCP"))
        self.protocolbox.setItemText(1, _translate("MainWindow", "UDP"))
        self.protocolbox.setItemText(2, _translate("MainWindow", "ICMP"))
        self.label.setText(_translate("MainWindow", "Source Port:"))
        self.label_4.setText(_translate("MainWindow", "Destination Port:"))
        self.label_5.setText(_translate("MainWindow", "Flags:"))
        self.SYN.setText(_translate("MainWindow", "SYN"))
        self.ACK.setText(_translate("MainWindow", "ACK"))
        self.FIN.setText(_translate("MainWindow", "FIN"))
        self.URG.setText(_translate("MainWindow", "URG"))
        self.PSH.setText(_translate("MainWindow", "PSH"))
        self.RST.setText(_translate("MainWindow", "RST"))
        self.label_6.setText(_translate("MainWindow", "Payload:"))
        self.payload_string.setText(_translate("MainWindow", "String:"))
        self.payload_no.setText(_translate("MainWindow", "No Payload"))
        self.payloadPcap.setText(_translate("MainWindow", "\'X\' * times: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.next), _translate("MainWindow", "Transport Header"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Clipboard"))
        self.send_button.setText(_translate("MainWindow", "Send!"))
        self.clipboard_button.setText(_translate("MainWindow", "Clipboard"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.menuEeee.setTitle(_translate("MainWindow", "eeee"))
        self.menuTtt.setTitle(_translate("MainWindow", "ttt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

